import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next - FakerJS Demo",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="sticky top-0 left-0 right-0 h-[72px] bg-gray-600 flex items-center justify-center space-x-6">
          <Link href={"/products"} className="underline">
            Products
          </Link>
          <Link href={"/demo"} className="underline">
            Demo
          </Link>
        </nav>
        <main className="flex items-center justify-center">{children}</main>
      </body>
    </html>
  )
}
